name: 'Required Approvals'
description: 'Checks that a PR has the required approvals for certain filepaths'
author: 'John Hannagan'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
