name: Self test

permissions:
  pull-requests: write
  checks: write


on:
  pull_request:
  pull_request_review:

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          requirements: |
            - patterns:
                - "*.js"
              requiredApprovals: 1
            - patterns:
                - ".github/**/*"
              requiredApprovals: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
