name: Build and test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn
      - run: |
          yarn all

  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          requirements: |
            - patterns:
                - "**/*"
              requiredApprovals: 2
            - patterns:
                - ".github/**/*"
              requiredApprovals: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
