name: Build and test
on:
  pull_request:
  pull_request_review:

permissions:
  checks: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn
      - run: |
          yarn all

  self-test:
    name: Check required approvals
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          requirements: |
            - patterns:
                - "*.js"
              requiredApprovals: 1
            - patterns:
                - ".github/**/*"
              requiredApprovals: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
